#!/usr/bin/env python3
"""Remove remaining student-facing scaffold text and refresh live snapshots.

This catches match-table helper wording of the form "definition -> ?" that is
useful while generating/importing questions but must never be shown to students.
"""

from __future__ import annotations

import json
import re
from copy import deepcopy
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
PAYLOAD = ROOT / "supabase/imports/unit1_stage5_approved_live_payload.json"
MIGRATION = ROOT / "supabase/migrations/20260504175000_remove_remaining_scaffold_and_refresh_snapshots.sql"
SUMMARY = ROOT / "docs/content-accuracy-scaffold-snapshot-hotfix-2026-05-04.json"

PAIRS_RE = re.compile(r"(?:^|\s+)Pairs:\s.*$", re.IGNORECASE | re.DOTALL)
ARROW_HELPER_RE = re.compile(r"(?:^|\s)[^.\n]+→\s*\?(?:\s*;[^.\n]+→\s*\?)+", re.IGNORECASE | re.DOTALL)


def clean_text(text: str) -> str:
    text = PAIRS_RE.sub("", text)
    text = ARROW_HELPER_RE.sub("", text)
    return re.sub(r"\n{3,}", "\n\n", text).strip()


def is_helper_text(text: str) -> bool:
    stripped = text.strip()
    return bool(PAIRS_RE.search(stripped) or ARROW_HELPER_RE.search(stripped))


def sql_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False).replace("'", "''")


def build_migration(rows: list[dict[str, Any]]) -> str:
    return f"""-- Remove remaining public scaffold text and refresh active session snapshots.
-- Generated by scripts/content_accuracy_hotfix_scaffold_snapshot_20260504.py.

begin;

with patch_payload as (
  select '{sql_json(rows)}'::jsonb as data
),
patch_rows as (
  select *
  from patch_payload,
  jsonb_to_recordset(patch_payload.data) as row(
    external_id text,
    stem text,
    content_blocks_json jsonb
  )
)
update public.questions q
set stem = p.stem,
    content_blocks_json = p.content_blocks_json,
    teacher_notes = concat_ws(' | ', nullif(q.teacher_notes, ''), 'Content accuracy hotfix 2026-05-04: removed remaining public scaffold helper text.')
from patch_rows p
where q.external_id = p.external_id;

-- Any session already started before these content repairs should receive the
-- corrected question payload before the student continues.
update public.session_questions sq
set question_snapshot_json = public.build_runtime_question_payload(sq.question_id, sq.id)
from public.sessions s
join public.questions q on q.id = sq.question_id
where s.id = sq.session_id
  and s.completed_at is null
  and q.is_active = true
  and sq.question_id is not null;

do $$
declare
  remaining_stem_scaffold integer;
  remaining_block_scaffold integer;
begin
  select count(*) into remaining_stem_scaffold
  from public.questions
  where is_active = true
    and (
      stem ilike '%Pairs:%'
      or stem ~ '→\\s*\\?'
    );

  if remaining_stem_scaffold <> 0 then
    raise exception 'Content hotfix failed: % active question stems still contain scaffold text', remaining_stem_scaffold;
  end if;

  select count(*) into remaining_block_scaffold
  from public.questions
  where is_active = true
    and (
      content_blocks_json::text ilike '%Pairs:%'
      or content_blocks_json::text ~ '→\\s*\\?'
    );

  if remaining_block_scaffold <> 0 then
    raise exception 'Content hotfix failed: % active prompt blocks still contain scaffold text', remaining_block_scaffold;
  end if;
end $$;

commit;
"""


def main() -> None:
    payload = json.loads(PAYLOAD.read_text(encoding="utf-8"))
    questions = payload["live_questions"]
    changed: list[dict[str, Any]] = []

    for question in questions:
        original = deepcopy(question)
        qid = question["question_external_id"]

        question["stem"] = clean_text(str(question.get("stem") or ""))
        blocks = []
        for block in question.get("content_blocks_json") or []:
            block = dict(block)
            text = str(block.get("text") or block.get("body") or "")
            if text and is_helper_text(text):
                continue
            if text and block.get("kind") == "text":
                block["text"] = clean_text(text)
            blocks.append(block)
        question["content_blocks_json"] = blocks

        if qid == "database-applications.past_paper.topics_03_04.q007":
            question["stem"] = "Match each database term with its correct definition."
            question["content_blocks_json"] = [
                block
                for block in question["content_blocks_json"]
                if not (block.get("kind") == "text" and str(block.get("text") or "").startswith("Terms:"))
            ]

        if question != original:
            changed.append(
                {
                    "external_id": qid,
                    "stem": question["stem"],
                    "content_blocks_json": question["content_blocks_json"],
                }
            )

    PAYLOAD.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    MIGRATION.write_text(build_migration(changed), encoding="utf-8")
    SUMMARY.write_text(
        json.dumps(
            {
                "changed_count": len(changed),
                "changed_question_ids": [row["external_id"] for row in changed],
                "migration": str(MIGRATION.relative_to(ROOT)),
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"Changed {len(changed)} question(s).")
    for row in changed:
        print(row["external_id"])


if __name__ == "__main__":
    main()
