-- Remove remaining public scaffold text and refresh active session snapshots.
-- Generated by scripts/content_accuracy_hotfix_scaffold_snapshot_20260504.py.

begin;

with patch_payload as (
  select '[{"external_id": "database-applications.past_paper.topics_03_04.q007", "stem": "Match each database term with its correct definition.", "content_blocks_json": [{"kind": "figure", "caption": "2019 Q3 DVD Rental Database (MEMBERS, LOAN, DVD)", "block_key": "figure_1"}, {"kind": "text", "text": "Match each database term with its correct definition.", "block_key": null}]}]'::jsonb as data
),
patch_rows as (
  select *
  from patch_payload,
  jsonb_to_recordset(patch_payload.data) as row(
    external_id text,
    stem text,
    content_blocks_json jsonb
  )
)
update public.questions q
set stem = p.stem,
    content_blocks_json = p.content_blocks_json,
    teacher_notes = concat_ws(' | ', nullif(q.teacher_notes, ''), 'Content accuracy hotfix 2026-05-04: removed remaining public scaffold helper text.')
from patch_rows p
where q.external_id = p.external_id;

-- Any session already started before these content repairs should receive the
-- corrected question payload before the student continues.
update public.session_questions sq
set question_snapshot_json = public.build_runtime_question_payload(sq.question_id, sq.id)
from public.sessions s, public.questions q
where s.id = sq.session_id
  and q.id = sq.question_id
  and s.completed_at is null
  and q.is_active = true
  and sq.question_id is not null;

do $$
declare
  remaining_stem_scaffold integer;
  remaining_block_scaffold integer;
begin
  select count(*) into remaining_stem_scaffold
  from public.questions
  where is_active = true
    and (
      stem ilike '%Pairs:%'
      or stem ~ '→\s*\?'
    );

  if remaining_stem_scaffold <> 0 then
    raise exception 'Content hotfix failed: % active question stems still contain scaffold text', remaining_stem_scaffold;
  end if;

  select count(*) into remaining_block_scaffold
  from public.questions
  where is_active = true
    and (
      content_blocks_json::text ilike '%Pairs:%'
      or content_blocks_json::text ~ '→\s*\?'
    );

  if remaining_block_scaffold <> 0 then
    raise exception 'Content hotfix failed: % active prompt blocks still contain scaffold text', remaining_block_scaffold;
  end if;
end $$;

commit;
